[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=node_modules/forge-std/",
  "ds-test/=lib/ds-test/src/"
]

[fmt]
line_length = 100
