[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
solc_version = "0.8.20"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
